image: python:3.9

cache:
  paths:
    - ~/.cache/pip/
    - ~/.cache/poetry/

before_script:
  - python -V  # Print out python version for debugging
  - cp acronomy/secrets.test.py acronomy/secrets.py
  - pip install setuptools
  - pip install poetry
  - poetry install


test:
  script:
    - poetry run python manage.py test

