[tool.poetry]
name = "acronomy"
version = "0.1.0"
description = ""
authors = ["Lukas Winkler <git@lw1.at>"]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
django = { extras = ["argon2"], version = "^3.0.6" }
psycopg2 = "^2.8.5"
django-simple-history = "^2.10.0"
markdown = "^3.2.2"
django-debug-toolbar = "^3.1.1"
djangorestframework = "^3.11.1"
requests = "^2.23.0"
ads = "^0.12.3"
Pillow = "^8.0.1"
gunicorn = "^20.0.4"
beautifulsoup4 = "^4.9.1"
django-bootstrap4 = "^2.0.0"
libsass = "^0.20.0"
markdown-katex = "^202009.1026"

[tool.poetry.dev-dependencies]
bpython = "^0.19"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
