# Generated by Django 3.0.6 on 2020-05-25 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acronym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=1000)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weblink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('acronym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='acros.Acronym')),
            ],
        ),
        migrations.CreateModel(
            name='DOIReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=255)),
                ('acronym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dois', to='acros.Acronym')),
            ],
        ),
    ]
