# Generated by Django 3.0.6 on 2020-05-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0002_historicalacronym_historicaldoireference_historicalweblink'),
    ]

    operations = [
        migrations.AddField(
            model_name='acronym',
            name='description_html',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acronym',
            name='description_md',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalacronym',
            name='description_html',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalacronym',
            name='description_md',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
