# Generated by Django 3.0.6 on 2020-05-27 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acros', '0004_auto_20200527_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPaperReference',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('bibcode', models.CharField(max_length=255)),
                ('arxiv_id', models.CharField(blank=True, max_length=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('acronym', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='acros.Acronym')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical paper reference',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PaperReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('bibcode', models.CharField(max_length=255)),
                ('arxiv_id', models.CharField(blank=True, max_length=20)),
                ('acronym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='acros.Acronym')),
            ],
        ),
        migrations.RemoveField(
            model_name='historicaldoireference',
            name='acronym',
        ),
        migrations.RemoveField(
            model_name='historicaldoireference',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='DOIReference',
        ),
        migrations.DeleteModel(
            name='HistoricalDOIReference',
        ),
    ]
