# Generated by Django 3.0.6 on 2020-05-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0005_auto_20200527_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaperreference',
            name='doi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paperreference',
            name='doi',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
