# Generated by Django 3.0.6 on 2020-05-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0006_auto_20200527_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='acronym',
            name='tags',
            field=models.ManyToManyField(related_name='acronyms', to='acros.Tag'),
        ),
    ]
