# Generated by Django 3.0.6 on 2020-05-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0010_auto_20200529_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaperreference',
            name='arxiv_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpaperreference',
            name='authors',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpaperreference',
            name='doi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpaperreference',
            name='pubdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalpaperreference',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpaperreference',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paperreference',
            name='arxiv_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paperreference',
            name='authors',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paperreference',
            name='doi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paperreference',
            name='pubdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='paperreference',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paperreference',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
