# Generated by Django 3.0.6 on 2020-05-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0012_auto_20200529_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='acronym',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='historicalpaperreference',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='paperreference',
            name='authors',
        ),
        migrations.AddField(
            model_name='paperreference',
            name='authors',
            field=models.ManyToManyField(null=True, to='acros.Author'),
        ),
    ]
