# Generated by Django 3.0.6 on 2020-05-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0013_auto_20200531_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperreference',
            name='authors',
            field=models.ManyToManyField(to='acros.Author'),
        ),
    ]
