# Generated by Django 3.0.6 on 2020-05-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0014_auto_20200531_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaperreference',
            name='authors',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='paperreference',
            name='authors',
        ),
        migrations.AddField(
            model_name='paperreference',
            name='authors',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
