# Generated by Django 3.0.6 on 2020-05-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0016_auto_20200531_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwikipedialink',
            name='thumbnail_height',
        ),
        migrations.RemoveField(
            model_name='historicalwikipedialink',
            name='thumbnail_width',
        ),
        migrations.RemoveField(
            model_name='wikipedialink',
            name='thumbnail_height',
        ),
        migrations.RemoveField(
            model_name='wikipedialink',
            name='thumbnail_width',
        ),
        migrations.AlterField(
            model_name='wikipedialink',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='thumbnail_height', upload_to='wikipedia_thumbnails/', width_field='thumbnail_width'),
        ),
    ]
