# Generated by Django 3.0.6 on 2020-05-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0018_auto_20200531_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, upload_to='host_icons/')),
            ],
        ),
    ]
