# Generated by Django 3.0.6 on 2020-05-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0019_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='fetched',
            field=models.BooleanField(default=False),
        ),
    ]
