# Generated by Django 3.0.6 on 2020-05-31 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0020_host_fetched'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweblink',
            name='host',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='acros.Host'),
        ),
        migrations.AddField(
            model_name='host',
            name='icon_height',
            field=models.IntegerField(blank=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='host',
            name='icon_width',
            field=models.IntegerField(blank=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weblink',
            name='host',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='acros.Host'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='host',
            name='icon',
            field=models.ImageField(blank=True, height_field='icon_height', upload_to='host_icons/', width_field='icon_width'),
        ),
    ]
