# Generated by Django 3.0.6 on 2020-05-31 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0021_auto_20200531_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='icon_height',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='icon_width',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
