# Generated by Django 3.0.6 on 2020-05-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0023_auto_20200531_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaperreference',
            name='authors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='paperreference',
            name='authors',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
