# Generated by Django 3.0.6 on 2020-06-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0024_auto_20200531_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalweblink',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='weblink',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
