# Generated by Django 3.0.6 on 2020-06-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0026_auto_20200608_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwikipedialink',
            name='thumbnail_caption',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwikipedialink',
            name='thumbnail_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='wikipedialink',
            name='thumbnail_caption',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='wikipedialink',
            name='thumbnail_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
