# Generated by Django 3.0.6 on 2020-06-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0029_historicaltag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwikipedialink',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
