# Generated by Django 3.0.6 on 2020-06-13 20:11

import acros.models.Acronym
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0030_auto_20200608_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalacronym',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='acronym',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalacronym',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
