# Generated by Django 3.0.6 on 2020-06-13 20:14

import acros.models.Acronym
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0031_auto_20200613_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acronym',
            name='name',
            field=models.CharField(max_length=100, validators=[acros.models.valid_acronym]),
        ),
        migrations.AlterField(
            model_name='historicalacronym',
            name='name',
            field=models.CharField(max_length=100, validators=[acros.models.valid_acronym]),
        ),
    ]
