# Generated by Django 3.0.7 on 2020-06-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0032_auto_20200613_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwikipedialink',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwikipedialink',
            name='thumbnail_height',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalwikipedialink',
            name='thumbnail_width',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='wikipedialink',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='thumbnail_height', null=True, upload_to='wikipedia_thumbnails/', width_field='thumbnail_width'),
        ),
        migrations.AlterField(
            model_name='wikipedialink',
            name='thumbnail_height',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='wikipedialink',
            name='thumbnail_width',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
