# Generated by Django 3.0.8 on 2020-07-06 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0033_auto_20200616_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcroOfTheDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('acronym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acros.Acronym')),
            ],
        ),
    ]
