# Generated by Django 3.0.8 on 2020-07-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0034_acrooftheday'),
    ]

    operations = [
        migrations.AddField(
            model_name='acrooftheday',
            name='order',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
