# Generated by Django 3.0.8 on 2020-07-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0037_auto_20200718_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acronym',
            name='stub',
            field=models.BooleanField(default=True, help_text='check if this is a minimal entry that should be extended'),
        ),
        migrations.AlterField(
            model_name='historicalacronym',
            name='stub',
            field=models.BooleanField(default=True, help_text='check if this is a minimal entry that should be extended'),
        ),
    ]
