# Generated by Django 3.0.8 on 2020-07-18 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0039_auto_20200718_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwikipedialink',
            name='thumbnail',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='acros.WikipediaImage'),
        ),
        migrations.AddField(
            model_name='wikipedialink',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiki_articles', to='acros.WikipediaImage'),
        ),
    ]
