# Generated by Django 3.0.8 on 2020-07-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0041_auto_20200718_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipediaimage',
            name='credit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wikipediaimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='wikipedia_images/'),
        ),
    ]
