# Generated by Django 3.0.8 on 2020-07-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0042_auto_20200718_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikipediaimage',
            name='artist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
