# Generated by Django 3.0.8 on 2020-07-19 18:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0044_auto_20200718_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='acronym',
            name='acro_letters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='historicalacronym',
            name='acro_letters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), null=True, size=None),
        ),
    ]
