# Generated by Django 3.0.8 on 2020-07-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0046_auto_20200719_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='acronym',
            name='pageviews',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='historicalacronym',
            name='pageviews',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
