# Generated by Django 3.1.5 on 2021-03-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0049_auto_20200727_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='acronym',
            name='ignore_in_checks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalacronym',
            name='ignore_in_checks',
            field=models.BooleanField(default=False),
        ),
    ]
