# Generated by Django 4.0.5 on 2022-06-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acros', '0050_auto_20210308_1855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalacronym',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical acronym', 'verbose_name_plural': 'historical acronyms'},
        ),
        migrations.AlterModelOptions(
            name='historicalpaperreference',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical paper reference', 'verbose_name_plural': 'historical paper references'},
        ),
        migrations.AlterModelOptions(
            name='historicaltag',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical tag', 'verbose_name_plural': 'historical tags'},
        ),
        migrations.AlterModelOptions(
            name='historicalweblink',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical weblink', 'verbose_name_plural': 'historical weblinks'},
        ),
        migrations.AlterModelOptions(
            name='historicalwikipedialink',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical wikipedia link', 'verbose_name_plural': 'historical wikipedia links'},
        ),
        migrations.AlterField(
            model_name='historicalacronym',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpaperreference',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltag',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalweblink',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalwikipedialink',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
