# Generated by Django 4.1.7 on 2023-03-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acros", "0051_alter_historicalacronym_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalwikipedialink",
            name="wikibase_item",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="wikipedialink",
            name="wikibase_item",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
